baseURL = 'https://joaomaia.dev/'
languageCode = 'pt-br'
title = 'Broken Semantics'
theme = 'hugo-theme-stack'
contentDir = "content"

[deployment]
  [[deployment.targets]]
    name = 'production'
    url = 'DEPLOY_S3_URL'
    invalidateCDN = true
    cloudFrontDistributionID = 'DEPLOY_CF_DISTRIBUTION_ID'